import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CursorDot from "../app/components/cursor";
import ClientOnly from "../app/components/ClientOnly";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Onewebbers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <ClientOnly>
          <CursorDot />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}