import { Poppins } from "next/font/google";
import "./globals.css";
import CursorDot from "../app/components/cursor";
import ClientOnly from "../app/components/ClientOnly";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Onewebbers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased bg-white`}
      >
        <ClientOnly>
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}